server {
    listen 80;

    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
    }

    location /api/auth {
        rewrite ^/api/auth/(.*) /$1 break;
        proxy_pass http://auth-service:4001;
    }

    location /api/url {
        rewrite ^/api/url/(.*) /$1 break;
        proxy_pass http://url-service:4002;
    }
}