server {
    listen 80;

    # Frontend
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Auth Service
    location /api/auth {
        proxy_pass http://auth-service:4001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # URL Service
    location /api/urls {
        proxy_pass http://url-service:4002/api/urls;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Analytics Service
    location /api/analytics {
        proxy_pass http://url-service:4002/api/analytics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Redirect Service for short URLs (excluding Next.js routes)
    location ~* "^/(?!api|auth|dashboard|_next|favicon\.ico)[a-zA-Z0-9_-]{3,30}$" {
        rewrite ^/(.*)$ /$1 break;
        proxy_pass http://redirect-service:4003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}